const anchor =[
  '/admin/material/modifyMaterial',
  '/admin/material/addMaterial',
  '/admin/faq/delFaq',
  '/admin/faq/modifyFaq',
  '/admin/faq/delFaqCate',
  '/admin/faq/addFaqCate',
  '/admin/faq/addFaq',
  '/admin/faq/modifyFaqCate',
  '/admin/faq/batchStatusUpdate',
  '/admin/faq/modifyFaqCateStatus',
  '/admin/faq/modifyFaqCateRecommend',
  '/admin/resourcegroup/add',
  '/admin/resourcegroup/edit',
  '/admin/resourcegroup/delete',
  '/admin/picture/add',
  '/admin/picture/delete',
  '/admin/picture/edit',
  '/admin/member/unlockMember',
  '/admin/member/lockMember',
  '/admin/member/deleteAdminMember',
  '/admin/member/modifyPassword',
  '/admin/member/modifyAdminMember',
  '/admin/member/addAdminMember',
  '/admin/contentpush/contentPushAdd',
  '/admin/contentpush/cancel',
  '/admin/contentpush/contentPushDelete',
  '/admin/contentpush/contentPushConfirm',
  '/admin/contentpush/contentPushModify',
  '/admin/role/addAdminRole',
  '/admin/role/modifyAdminRole',
  '/admin/member/modifySelfPassword',
  '/admin/member/modifyPassword',
  '/admin/appversion/add',
  '/admin/appversion/modify'
]

export default anchor;